(* Generated by: ocaml-crunch
   Creation date: Wed, 31 Jan 2024 21:35:45 GMT *)

module Internal = struct
  let d_cc2c0585c8ad2fc00aa4f744bd29c8ab = "// Generated by Melange\n\n\nvar $$Event = {};\n\nvar $$WebSocket = {};\n\nvar $$Element = {};\n\nvar $$Document = {};\n\nfunction mount(socket, _event) {\n  socket.send(\" \\\"Mount\\\" \");\n}\n\nvar $$event = (function (element, event) {\n  let id = element.getAttribute(\"data-sidewinder-id\");\n  return JSON.stringify({ \"Event\": [id, \"\"] })\n});\n\nfunction handle_click(socket, el, e) {\n  socket.send($$event(el, e));\n}\n\nvar rebind = (function (socket, element) { \n  let elements = [...element.querySelectorAll(\"*[data-sidewinder-id]\")];\n  elements.forEach((el) => {\n    el.addEventListener(\"click\", (ev) => handle_click(socket, el, ev));\n  });\n});\n\nvar patch = (function (event) {\nlet json = JSON.parse(event.data);\nreturn json.Patch[0]\n});\n\nfunction handle_event(socket, element, e) {\n  var diff = patch(e);\n  element.innerHTML = diff;\n  return rebind(socket, element);\n}\n\nfunction spawn(element_id, path) {\n  var element = document.getElementById(element_id);\n  var url = \"ws://192.168.1.19:8080\" + path;\n  var socket = new WebSocket(url);\n  socket.addEventListener(\"open\", (function (param) {\n          return mount(socket, param);\n        }));\n  socket.addEventListener(\"message\", (function (param) {\n          return handle_event(socket, element, param);\n        }));\n}\n\nexport {\n  $$Event ,\n  $$WebSocket ,\n  $$Element ,\n  $$Document ,\n  mount ,\n  $$event ,\n  handle_click ,\n  rebind ,\n  patch ,\n  handle_event ,\n  spawn ,\n}\n/* No side effect */\n"

  let file_chunks = function
    | "sidewinder_web_runtime.mjs" | "/sidewinder_web_runtime.mjs" -> Some [ d_cc2c0585c8ad2fc00aa4f744bd29c8ab; ]
    | _ -> None

  let file_list = [ "sidewinder_web_runtime.mjs"; ]
end

let file_list = Internal.file_list

let read name =
  match Internal.file_chunks name with
  | None -> None
  | Some c -> Some (String.concat "" c)

let hash = function
  | "sidewinder_web_runtime.mjs" | "/sidewinder_web_runtime.mjs" -> Some "cc2c0585c8ad2fc00aa4f744bd29c8ab"
  | _ -> None

let size = function
  | "sidewinder_web_runtime.mjs" | "/sidewinder_web_runtime.mjs" -> Some 1432
  | _ -> None
